# Site settings
title: Turpial
description: "Turpial is a lightweight and beautiful microblogging client written in Python."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://richzendy.github.io/Turpial-Website/" # the name of your domain
logo_url: /img/logo.png

# Hero
hero: 
    hero_img: landscape-background.png
    hero_title: Turpial
    hero_description: Turpial is a lightweight and beautiful microblogging client written in Python.

# Social settings
twitter: http://twitter.com
youtube: http://youtube.com
feed: yes

# Footer
copyright: © 2016 Turpial 

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:

# Blog
paginate: 5
paginate_path: "/news/page/:num/"
permalink:    "/news/:year/:month/:title/"